name: AWS S3 Cleanup

on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
        - cron: '0 * * * *'

permissions:
    id-token: write

jobs:
    s3_cleanup:
        runs-on: ubuntu-latest
        steps:
            - name: Authentication
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::092376285579:role/aws-s3-cloning
                  aws-region: us-east-1
            - name: Install RClone
              run: sudo -v ; curl https://rclone.org/install.sh | sudo bash
            - name: Clone the repo
              uses: actions/checkout@v4
